### PR TITLE
added check for minimum fft size

### PR DESCRIPTION
**Pull request by unevens**

### CODE REVIEW

**Comment by hayguen** [comment]
Hi @unevens ,

i fear, you missed some places to change the return type of `prepareLength`.
adding return bool to prepareLength() is good .. but then, we should also check for a valid fft length.

adding assert to constructor: i'm unsure about this one, cause assert does only check/fail in Debug.
on the other side, i'm no friend of throwing exceptions. any idea?

**Comment by unevens** [comment]
hey @hayguen, 

i don't think that there is a good solution for the contructor, but in my opinion the `assert` is (a lot) better than nothing.

excpetions would be the correct choice for the language, but it is probably better to avoid them for a project like this one in which we try to stay compatible with embedded platforms? (am i wrong? did you have some other concerns?) 
maybe we could use some macro and throw an exception just on certain compilers/platforms... but in my opinion that would be too much of a hassle. and already having the `assert` and the `minFFtsize` function seems to be enough for me.

regarding `prepareLength`: i just changed the signature of `Fft<T>::prepareLength`, not the one of `Setup<T>::prepareLength`, because i don't think that we need to check in more than one place.

**Comment by hayguen** [comment]
> in my opinion the assert is (a lot) better than nothing.

agree

>  it is probably better to avoid them for a project like this one in which we try to stay compatible with embedded platforms?

yes. but i'm not happy with c++ exceptions in general, because there is no way to statically detect missed uncatched exceptions. at least i don't know such a tool.

>  i just changed the signature of Fft<T>::prepareLength, not the one of Setup<T>::prepareLength, because i don't think that we need to check in more than one place

thanks for explaining. i'll check this again ..

**Comment by hayguen** [comment]
as you see in pffft_priv_impl.h line 1017:
```
SETUP_STRUCT *FUNC_NEW_SETUP(int N, pffft_transform_t transform) {
  SETUP_STRUCT *s = (SETUP_STRUCT*)malloc(sizeof(SETUP_STRUCT));
  int k, m;
  /* unfortunately, the fft size must be a multiple of 16 for complex FFTs 
     and 32 for real FFTs -- a lot of stuff would need to be rewritten to
     handle other cases (or maybe just switch to a scalar fft, I don't know..) */
  if (transform == PFFFT_REAL) { assert((N%(2*SIMD_SZ*SIMD_SZ))==0 && N>0); }
  if (transform == PFFFT_COMPLEX) { assert((N%(SIMD_SZ*SIMD_SZ))==0 && N>0); }
```

and also at end of this function line 1058
```
  /* check that N is decomposable with allowed prime factors */
  for (k=0, m=1; k < s->ifac[1]; ++k) { m *= s->ifac[2+k]; }
  if (m != N/SIMD_SZ) {
    FUNC_DESTROY(s); s = 0;
  }
```

i would suggest replacing the asserts by `return NULL;` in the checks ..
and return the result all the way up .. to catch it at the end in C++, as you did

hmmm, i notice, that we are missing a C++ method/function to check, if `class Setup<float>::self` returned from `self = pffft_new_setup(length, PFFFT_REAL);` in `Setup<>::prepareLength(int length)` functions was not NULL!

**Comment by hayguen** [comment]
please check this PR, which modifies @unevens one: https://github.com/marton78/pffft/pull/26

**Comment by unevens** [comment]
hey @hayguen, 
oh yes i agree. you really thought of everything! this is gonna get pffft a lot more robust.

**Pull request closed without merging**
