### PR TITLE
add mingw support

### PR DESCRIPTION
**Pull request by xidang**
add support for mingw and ming64

### CODE REVIEW

**Comment by unevens** [comment]
hi. this seems like a nice feature. i'm a bit worried that it may break support for the llvm backend in msvc, which i don't remember if it is ddetected by cmake as MSVC of not. i can't test that right now.

**Comment by hayguen** [comment]
i've installed https://www.msys2.org , referring to http://mingw-w64.org/doku.php/download it comes with the latest gcc compiler.
i got link errors with c++ programs .. missing libstdc++. fixed this locally .. but want to test with msvc ..

**Comment by xidang** [comment]
> hi. this seems like a nice feature. i'm a bit worried that it may break support for the llvm backend in msvc, which i don't remember if it is ddetected by cmake as MSVC of not. i can't test that right now.

My gcc version is  "gcc (GCC with MCF thread model, built by LH_Mouse.) 11.1.1 20210604" ,  cl version is  " 19.29.30038.1" and cmake version is "cmake version 3.20.3". This commit works fine with these configurations.  As for clang itself, it will not be detected as MSVC by cmake. It may require other modifications before it could be build with clang.

**Comment by hayguen** [comment]
@xidang would you please test my PR https://github.com/marton78/pffft/pull/50 , which includes yours on your mingw platform?

**Comment by xidang** [comment]
> @xidang would you please test my PR #50 , which includes yours on your mingw platform?

I tested PR #50 . It builds well but there are SegFaults when running Test #9: bench_pfconv_non_sym and Test #8: bench_pfconv_symetric.

**Comment by hayguen** [comment]
yes, i realized the segfaults. these were there before also. but therse are only relevant for the convolution - not fft itself.
interestingly, the segfaults are only in release. windows debug and linux run fine. not sure how to debug this ..
however, the segfaults are no show stopper for this PR.

**Comment by hayguen** [comment]
fixed the segfaults on windows in PR https://github.com/marton78/pffft/pull/50
having everything necessary .. this PR gets obsolete

**Pull request closed without merging**
